helm:
  parameters:
  - name: image.repository
    value: 579385932895.dkr.ecr.us-east-1.amazonaws.com/nodejs-app
    forcestring: true
  - name: image.tag
    value: build-5
    forcestring: true
serviceAccount:
  create: true
  name: nodejs-app

