apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-external-secret
  namespace: nodejs-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: rds-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: aws-gitops-pipeline-dev-rds-credentials
