apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-external-secret
  namespace: nodejs-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: rds-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_HOST
    remoteRef:
      key: aws-gitops-pipeline-dev-rds-credentials
      property: host
  - secretKey: DB_PORT
    remoteRef:
      key: aws-gitops-pipeline-dev-rds-credentials
      property: port
  - secretKey: DB_NAME
    remoteRef:
      key: aws-gitops-pipeline-dev-rds-credentials
      property: dbname
  - secretKey: DB_USER
    remoteRef:
      key: aws-gitops-pipeline-dev-rds-credentials
      property: username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: aws-gitops-pipeline-dev-rds-credentials
      property: password
