apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - secretstore.yaml
  - externalsecret-rds.yaml
  - externalsecret-redis.yaml

images:
  - name: 287043460305.dkr.ecr.us-east-1.amazonaws.com/nodejs-app
    newTag: latest
