apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodejs-app-sa
  namespace: nodejs-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::287043460305:role/aws-gitops-pipeline-dev-eso-role
  labels:
    app: nodejs-app
