apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nodejs-app=287043460305.dkr.ecr.us-east-1.amazonaws.com/nodejs-app
    argocd-image-updater.argoproj.io/nodejs-app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/nodejs-app.allow-tags: regexp:^build-[0-9]+$
    argocd-image-updater.argoproj.io/nodejs-app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/nodejs-app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/nodejs-app.pull-secret: pullsecret:argocd/ecr-credentials
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/Ahmed-Maher-Sabeq/Full-GitOps-Pipeline-on-AWS-with-Terraform-and-Secrets-Management-ITI-Final-Project.git
    targetRevision: main
    path: k8s/helm-chart/nodejs-app
    helm:
      parameters:
      - name: image.repository
        value: 287043460305.dkr.ecr.us-east-1.amazonaws.com/nodejs-app
      - name: image.tag
        value: latest
  
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-app
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
